#!/bin/sh

su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::Add --name "Nivel 1"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::Add --name "Nivel 2"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::Add --name "Nivel 3"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::Add --name "Lixo"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Role::Add --name "Nivel 1"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Role::Add --name "Nivel 3"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Role::Add --name "Nivel 2"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Rale::Add --name "Lixo"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Queue::Add --name "Nivel 1" --group "Nivel 1"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Queue::Add --name "Nivel 2" --group "Nivel 2"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Queue::Add --name "Nivel 3" --group "Nivel 3"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Queue::Add --name "Lixo" --group "Lixo"'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 1" --group-name "Nivel 1" --permission rw'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 2" --group-name "Nivel 2" --permission rw'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 3" --group-name "Nivel 3" --permission rw'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 1" --group-name "Nivel 2" --permission move_into'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 2" --group-name "Nivel 3" --permission move_into'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 2" --group-name "Nivel 1" --permission move_into'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 3" --group-name "Nivel 1" --permission move_into'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 3" --group-name "Nivel 2" --permission move_into'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 3" --group-name "Lixo" --permission move_into'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 2" --group-name "Lixo" --permission move_into'
su otrs -s /bin/bash -c '/opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --role-name "Nivel 1" --group-name "Lixo" --permission move_into'


