{
 "title": "OTRS Dashboard FAMEtec",
 "description": "Dashboard",
 "tags": [ "otrs" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "Queue",
    "query": "select name as __text, id as __value from queue"
   },
   {
    "name": "state",
    "label": "State",
    "query": "select name as __text, id as __value  from ticket_state"
   },
   { "name": "ANO", "query": "2018, 2019, 2020, 2021, 2022" },
   {
    "name": "MES",
    "query": "01,02,03,04,05,06,07,08,09,10,11,12"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 }, "content": "<H1>FAMETEC.COM.BR</H1>\n" },
  { "title": "Data / Hora", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 7, "x": 5, "y": 0 } },
  {
   "title": "Chamados por Atendente",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n  u.login, \n  count(t.id) Chamados\nfrom \n  ticket t, \n  queue q, \n  users u \nwhere \n  u.id = t.responsible_user_id and \n  q.id = t.queue_id and\n  t.ticket_state_id in (1,4,11,12,13,14) and \n  q.id in ($queue)\ngroup by u.login"
    }
   ]
  },
  {
   "title": "Novos",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1) and queue_id in ($queue)"
    }
   ]
  },
  {
   "title": "Classificados",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id = 11 and queue_id in ($queue);"
    }
   ]
  },
  {
   "title": "Abertos",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " select count(*) as cont from ticket where ticket_state_id in (1,4,11,12,13,14) and queue_id in ($queue);"
    }
   ]
  },
  {
   "title": "Chamados por Atendente",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select \n  q.name as Fila, \n  ts.name as State, \n  t.*, \n  q.*\nfrom \n  ticket t, \n  queue q, \n  users u, \n  ticket_state ts \nwhere \n  u.id = t.responsible_user_id and \n  q.id = t.queue_id and\n  t.ticket_state_id = ts.id and \n  ts.id in ($state) and \n  q.id in ($queue)"
    },
    { "rawSql": "SELECT 1" }
   ]
  },
  {
   "title": "Satisfação",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "rawSql": "select\n UNIX_TIMESTAMP(sv.create_time) as time_sec, sa.answer as Respostas\nfrom \n survey_answer sa,\n survey_vote sv \nwhere \n sa.id = sv.vote_value and \n sv.question_id = 1 and \n DATE_FORMAT(sv.create_time, \"%Y\") IN ($ANO) and \n DATE_FORMAT(sv.create_time, \"%m\") IN ($MES)\n-- group by sa.answer\n-- order by Ano, Mes desc"
    }
   ]
  }
 ]
}